// src/pages/games/loldle/quotes/quotes.ts
//
// Map<championId, string[]> de falas icônicas (ou ficticias) por campeao.
// Cada campeao recebe 3-5 quotes. Quando a fonte canonica nao tem uma
// citacao memoravel, usamos um placeholder tematico do campee
// (ex: 'A frase de efeito de <Campeao>') para nao quebrar a pool.
//
// Modo Quote: o jogador recebe uma quote aleatoria do campeao-alvo
// e tenta adivinhar de quem e em ate 8 tentativas.

export const CHAMPION_QUOTES: Record<string, string[]> = {
  aatrox: [
    'Querer e poder. Voce deve acreditar que e impossivel para alcancar o impossivel.',
    'A guerra nao se vence com a mente. Vence-se com o corpo.',
    'Meu destino? E destruir tudo que existe.',
    'Eu sou a voz que recita o nome dos caidos.',
    'O ceu vai desabar. E eu estarei de pe quando isso acontecer.',
  ],
  ahri: [
    'Nove vidas para te amar, e uma para te perder.',
    'Ninguem escapa de mim duas vezes.',
    'A cauda e uma lembranca. O coracao e quem eu sou agora.',
    'Coracao partido? Nao. Apenas sede.',
    'Meu charme e apenas um presente que eu faco a voce.',
  ],
  akali: [
    'Nenhum exercito pode me parar quando a sombra e minha aliada.',
    'Voce corre. Eu persisto. O resultado e o mesmo.',
    'A ordem me ensinou a obedecer. Eu aprendi a cortar.',
    'Nuvens passam. Sombras ficam.',
    'A melhor luta e aquela que o inimigo nem percebe que comecou.',
  ],
  ashe: [
    'Nossa flecha unica carrega a furia de mil ancestrais.',
    'Quando o inverno chega, eu sou a rainha.',
    'A linha entre coragem e loucura? Eu pulo ela.',
    'Frio. Calmo. Certo.',
    'Glacia Casenn. A vontade da minha mae vive em cada flecha.',
  ],
  caitlyn: [
    'Se ha um misterio, eu vou resolve-lo.',
    'Pow-pow! Hora de mirar.',
    'A verdade mora no cano desta arma.',
    'Sheriff de Piltover na folga? Nao existe folga.',
    'O caso mais facil do mundo. Ele ja se entregou.',
  ],
  darius: [
    'Seu mundo sera um deserto de Noxus.',
    'Noxus!',
    'Aqueles que me encaram geralmente nao vivem para contar.',
    'So existe uma licao: nunca desista.',
    'A forca nao vem da lamina. Vem de quem a empunha.',
  ],
  diana: [
    'A lua me guia. E eu corto o que ela ilumina.',
    'O sol e uma mentira. A lua e a verdade.',
    'Eu ja morri uma vez. Nao tenho medo de morrer de novo.',
    'A noite me pertence.',
    'Cavaleiros da lua, avancem.',
  ],
  ekko: [
    'Eu sempre tenho um segundo tempo. Ou um terceiro.',
    'O tempo e uma coisa estranha. Eu o quebro todos os dias.',
    'Nada e o fim enquanto a ampulheta ainda corre.',
    'Voltar e mudar. E um dom. E um peso.',
    'O relogio da minha runa nunca para.',
  ],
  ezreal: [
    'A aventura espera. E eu nao espero por ninguem.',
    'Tesouro, fama, mulheres. Talvez nessa ordem.',
    'Explorar? Claro. Com estilo? Sempre.',
    'Eu sou o melhor arqueologo que Piltover ja viu.',
    'O mapa mostra um X. Eu sou o Y.',
  ],
  fiora: [
    'A mais nobre das mortes e a que se escolhe.',
    'Minha lamina responde onde as palavras nao dao conta.',
    'Um duelo e uma conversa. Apenas com sangue.',
    'Vou duelar. Quem quer ser o proximo?',
    'A perfeccao nao e um acidente. E uma rotina.',
  ],
  garen: [
    'Por Demacia!',
    'A vitoria vem para os que merecem.',
    'Minha espada serve a coroa. E a justica.',
    'Eu nunca recuo. Eu apenas avanco mais devagar quando e preciso.',
    'Hoje, o inimigo. Amanha, historia.',
  ],
  gwen: [
    'Eu sou a menina das agulhas.',
    'Os mortos podem voltar. Mas com a linha certa.',
    'A costureira mais letal de Shadow Isles.',
    'O que voce tem? Eu cuido com a agulha e a linha.',
    'Cada corte meu carrega o amor da minha avo.',
  ],
  jinx: [
    'Vamos fazer BANG!',
    'Regras? Para que servem regras quando ha explosoes?',
    'Pow-pow adora voce. Ela disse.',
    'Voce e minha nova cobaia. Ai, obrigado por participar.',
    'Fisico-quimica pura. Quimica de explosao.',
  ],
  kai_sa: [
    'Eu sou a filha do vacuo. E ele e minha armadura.',
    'O vazio me escolheu. Eu escolhi a caça.',
    'Nao sou uma caçadora. Eu sou o caçador.',
    'A luz do vacuo e a unica que importa.',
    'Kha Zix nao me acha. Eu acho ele.',
  ],
  katarina: [
    'Brilho e sangue. E a combinacao perfeita.',
    'Nenhum golpe duas vezes. Apos a faca, a proxima lâmina.',
    'Eu nao espero. Eu ajo.',
    'Cuidado onde pisa. Minhas laminas chegam primeiro.',
    'A Noxus nao precisa de reis. Precisa de assassinos.',
  ],
  kayle: [
    'A justicia nao dorme. Eu tampouco.',
    'Vou separar o joio do trigo. Com fogo se preciso.',
    'A vinganca e uma forma de justica. E a unica que eu aceito.',
    'O ceu me enviou. E o ceu se arrependeu.',
    'Eu nao julgo. Eu decreto.',
  ],
  kha_zix: [
    'Caça. Come. Evolua. E o ciclo do vazio.',
    'Eu caço. E quando nao ha mais o que caçar, eu evoluo.',
    'A adrenalina do combate e minha recompensa.',
    'O medo? E o tempero da presa.',
    'Voce me viu? E porque ja e tarde.',
  ],
  lee_sin: [
    'Sua vontade. Meu punho.',
    'Mostre-me a sua determinacao.',
    'O caminho do guerreiro e feito de escolhas.',
    'A cego e a marcial. Combinações perfeitas.',
    'Flame carpet! E o classico.',
  ],
  leona: [
    'O sol nunca se aposenta. Eu tampouco.',
    'Para cada golpe, eu tenho um escudo.',
    'A luz guia. A espada executa.',
    'Eu sou a alvorada. E o crepusculo dos meus inimigos.',
    'Onde pisao os Leoes, o sol nasce.',
  ],
  lucian: [
    'A luz queima. E a minha queima mais que tudo.',
    'Nao ha descanso para os caçadores.',
    'Thresh! Sua hora chegou.',
    'Senna, eu vou te encontrar. Sempre.',
    'Cada tiro e um passo ate a vinganca.',
  ],
  lulu: [
    'Pix! O que vamos fazer hoje?',
    'Tudo e melhor com um pouco de magia.',
    'Fofura e estrategia. Sempre.',
    'Eu nao me meto. Eu encanto.',
    'Shen, eu nao sou a culpada. Foi o Pix.',
  ],
  lux: [
    'A luz vence. Sempre.',
    'Cuidado com o brilho. Ele cega.',
    'A luz guia. Mesmo quando eu duvido.',
    'Demacia! E magia. Ninguem precisa saber.',
    'Luz final! E sempre no momento certo.',
  ],
  malphite: [
    'Pedra. Paciencia. Poder.',
    'A montanha nao corre. E mesmo assim vence.',
    'A paciencia e uma virtude. Eu a transformei em arte.',
    'Eternidade. Solidez. Impacto.',
    'Ixtal me formou. Eu sou a forma.',
  ],
  master_yi: [
    'A lamina queimo? A lamina e imortal.',
    'O Alpha Strike nao falha. E o usuario que atrasa.',
    'A velocidade? E a essencia do combate.',
    'Foco. Equilibrio. Vitoria.',
    'A forca interior e maior que qualquer lamina.',
  ],
  miss_fortune: [
    'Saudações, parceiro. Quer dançar?',
    'A caça comeca quando o alvo percebe que e a caça.',
    'Bileturro! Hora de trocar de alvo.',
    'O mar e meu escritorio. E os piratas sao meus clientes.',
    'Pow-pow nao e nada. A minha metralhadora sim.',
  ],
  morgana: [
    'A escuridao nao mente. As pessoas sim.',
    'Demacia me prendeu. Eu me libertei.',
    'As correntes de Demacia ainda apertam. Mas em quem?',
    'E meu espelho. E ele e minha arma.',
    'A vinganca? Nao. Apenas justica.',
  ],
  nasus: [
    'Conhecimento e poder. A vida e uma biblioteca.',
    'A areia do tempo sobe. E eu cresco com ela.',
    'Furacao? Que furacao. Isso e um sopro de Areia.',
    'A paciencia de Shurima. A forca de Shurima.',
    'Quem guarda o livro, guarda a eternidade.',
  ],
  orianna: [
    'A perfeição e uma esfera. E uma jornada.',
    'O tempo e um relogio. Eu sou os ponteiros.',
    'A bola que eu carrego e meu coracao. E meu algoritmo.',
    'O passado e a engrenagem. O futuro e o calculo.',
    'Tick. Tock. Decisao.',
  ],
  riven: [
    'A espada quebrada tem mil historias.',
    'A fragilidade e a origem da forca.',
    'Noxus me fez guerreira. Runeterra me fez quebrada.',
    'A lamina quebrou. Eu nao.',
    'A forca nao esta na espada. Esta em quem a empunha.',
  ],
  senna: [
    'A neblina se dissipa. Eu fico.',
    'O amor nao morre. A neblina nao vence.',
    'Thresh! E a sua vez.',
    'A luz e a sombra dao o contraste da vida.',
    'Lucian, eu estou voltando. Aguenta firme.',
  ],
  sett: [
    'Ha! Quem quer brincar?',
    'O poder e a forca. E o soco. Sempre o soco.',
    'Minha mae me ensinou a lutar. A vida me ensinou a vencer.',
    'O ringue e meu escritorio. E o tatame e meu trono.',
    'HAYAAAH! E o grito de guerra do pai.',
  ],
  shen: [
    'O equilibrio e a unica licao.',
    'A espada nao corta apenas. Ela tambem protege.',
    'O ninja que nao se mostra. Esse e o mais perigoso.',
    'Nuvens passam. Shen fica.',
    'A uniao faz a forca. Mesmo entre sombras.',
  ],
  sivir: [
    'Ouro fala. E eu sou a voz dele.',
    'A lamina gira. E a historia se conta.',
    'Shurima foi meu berco. Shurima e minha corrida.',
    'O ouro nao mente. A vida sim.',
    'A cruz de Shurima! A dancinha comeca agora.',
  ],
  soraka: [
    'A cura vem. Sempre.',
    'A estrela guia. Mesmo no ceu mais escuro.',
    'A vida que eu tiro. E a vida que eu dou.',
    'As estrelas ouvem. Eu ouço.',
    'Deseja uma cura? Ou uma verdade?',
  ],
  teemo: [
    'O capitao Teemo no posto!',
    'Shhhh! Vou plantar umas sementes.',
    'Os yordles sao fofos. Eu sou letal.',
    'Bandle City, eu venho representando.',
    'A neblina? E o meu escritorio.',
  ],
  thresh: [
    'A historia e longa. E cheia de gritos.',
    'A lanterna convida. E eu nunca falto.',
    'A alma de hoje e o brinquedo de amanha.',
    'Cuidado onde pisa. A colecao cresce.',
    'Quem quer dançar comigo? E dançar com a coleira.',
  ],
  vayne: [
    'Os monstros existem. E eu os caço.',
    'A noite e minha. E os caçadores vao virar caça.',
    'A besta que eu procuro? E o mal em pessoa.',
    'Vou caçar. Sozinha. Sempre.',
    'A flecha final. E sempre certeira.',
  ],
  yasuo: [
    'Death is like the wind. Always by my side.',
    'A honra e o caminho. Mesmo na tempestade.',
    'A espada e a unica verdade que eu confio.',
    'A ultima brisa da alma. E minha.',
    'O ar que eu corto? E a historia de Noxus.',
  ],
  yone: [
    'Vim buscar meu irmao. E a verdade.',
    'A morte e uma fronteira. Eu ja passei por ela.',
    'A espada dupla? E a dualidade da alma.',
    'A mascara que eu uso? E o segredo que eu guardo.',
    'Yasuo! Eu sei o que voce fez. Ou quase.',
  ],
  zed: [
    'Nenhum caminho e tao escuro quanto a minha mente.',
    'As sombras obedecem. E eu as comendo.',
    'A ordem e uma mentira. A sombra e a verdade.',
    'A lamina final. Sempre a ultima.',
    'Voce nao me viu. E porque eu ja venci.',
  ],

  // === placeholders para campees sem quotes proprias (agent A) ===
  corki: ['[quote do campee corki]', '[outra frase do campee corki]', '[mais uma fala do campee corki]', '[bonus: e corki no microfone]'],
  heimerdinger: ['[quote do campee heimerdinger]', '[outra frase do campee heimerdinger]', '[mais uma fala do campee heimerdinger]', '[bonus: e heimerdinger no microfone]'],
  kennen: ['[quote do campee kennen]', '[outra frase do campee kennen]', '[mais uma fala do campee kennen]', '[bonus: e kennen no microfone]'],
  kled: ['[quote do campee kled]', '[outra frase do campee kled]', '[mais uma fala do campee kled]', '[bonus: e kled no microfone]'],
  nunu: ['[quote do campee nunu]', '[outra frase do campee nunu]', '[mais uma fala do campee nunu]', '[bonus: e nunu no microfone]'],
  poppy: ['[quote do campee poppy]', '[outra frase do campee poppy]', '[mais uma fala do campee poppy]', '[bonus: e poppy no microfone]'],
  rammus: ['[quote do campee rammus]', '[outra frase do campee rammus]', '[mais uma fala do campee rammus]', '[bonus: e rammus no microfone]'],
  rumble: ['[quote do campee rumble]', '[outra frase do campee rumble]', '[mais uma fala do campee rumble]', '[bonus: e rumble no microfone]'],
  tristana: ['[quote do campee tristana]', '[outra frase do campee tristana]', '[mais uma fala do campee tristana]', '[bonus: e tristana no microfone]'],
  veigar: ['[quote do campee veigar]', '[outra frase do campee veigar]', '[mais uma fala do campee veigar]', '[bonus: e veigar no microfone]'],
  gnar: ['[quote do campee gnar]', '[outra frase do campee gnar]', '[mais uma fala do campee gnar]', '[bonus: e gnar no microfone]'],
  yuumi: ['[quote do campee yuumi]', '[outra frase do campee yuumi]', '[mais uma fala do campee yuumi]', '[bonus: e yuumi no microfone]'],
  missfortune: ['[quote do campee missfortune]', '[outra frase do campee missfortune]', '[mais uma fala do campee missfortune]', '[bonus: e missfortune no microfone]'],
  graves: ['[quote do campee graves]', '[outra frase do campee graves]', '[mais uma fala do campee graves]', '[bonus: e graves no microfone]'],
  gangplank: ['[quote do campee gangplank]', '[outra frase do campee gangplank]', '[mais uma fala do campee gangplank]', '[bonus: e gangplank no microfone]'],
  nautilus: ['[quote do campee nautilus]', '[outra frase do campee nautilus]', '[mais uma fala do campee nautilus]', '[bonus: e nautilus no microfone]'],
  illaoi: ['[quote do campee illaoi]', '[outra frase do campee illaoi]', '[mais uma fala do campee illaoi]', '[bonus: e illaoi no microfone]'],
  pyke: ['[quote do campee pyke]', '[outra frase do campee pyke]', '[mais uma fala do campee pyke]', '[bonus: e pyke no microfone]'],
  tahmkench: ['[quote do campee tahmkench]', '[outra frase do campee tahmkench]', '[mais uma fala do campee tahmkench]', '[bonus: e tahmkench no microfone]'],
  nilah: ['[quote do campee nilah]', '[outra frase do campee nilah]', '[mais uma fala do campee nilah]', '[bonus: e nilah no microfone]'],
  fizz: ['[quote do campee fizz]', '[outra frase do campee fizz]', '[mais uma fala do campee fizz]', '[bonus: e fizz no microfone]'],
  twistedfate: ['[quote do campee twistedfate]', '[outra frase do campee twistedfate]', '[mais uma fala do campee twistedfate]', '[bonus: e twistedfate no microfone]'],
  jarvaniv: ['[quote do campee jarvaniv]', '[outra frase do campee jarvaniv]', '[mais uma fala do campee jarvaniv]', '[bonus: e jarvaniv no microfone]'],
  xinzhao: ['[quote do campee xinzhao]', '[outra frase do campee xinzhao]', '[mais uma fala do campee xinzhao]', '[bonus: e xinzhao no microfone]'],
  galio: ['[quote do campee galio]', '[outra frase do campee galio]', '[mais uma fala do campee galio]', '[bonus: e galio no microfone]'],
  sona: ['[quote do campee sona]', '[outra frase do campee sona]', '[mais uma fala do campee sona]', '[bonus: e sona no microfone]'],
  quinn: ['[quote do campee quinn]', '[outra frase do campee quinn]', '[mais uma fala do campee quinn]', '[bonus: e quinn no microfone]'],
  shyvana: ['[quote do campee shyvana]', '[outra frase do campee shyvana]', '[mais uma fala do campee shyvana]', '[bonus: e shyvana no microfone]'],
  sylas: ['[quote do campee sylas]', '[outra frase do campee sylas]', '[mais uma fala do campee sylas]', '[bonus: e sylas no microfone]'],
  anivia: ['[quote do campee anivia]', '[outra frase do campee anivia]', '[mais uma fala do campee anivia]', '[bonus: e anivia no microfone]'],
  sejuani: ['[quote do campee sejuani]', '[outra frase do campee sejuani]', '[mais uma fala do campee sejuani]', '[bonus: e sejuani no microfone]'],
  udyr: ['[quote do campee udyr]', '[outra frase do campee udyr]', '[mais uma fala do campee udyr]', '[bonus: e udyr no microfone]'],
  trundle: ['[quote do campee trundle]', '[outra frase do campee trundle]', '[mais uma fala do campee trundle]', '[bonus: e trundle no microfone]'],
  volibear: ['[quote do campee volibear]', '[outra frase do campee volibear]', '[mais uma fala do campee volibear]', '[bonus: e volibear no microfone]'],
  lissandra: ['[quote do campee lissandra]', '[outra frase do campee lissandra]', '[mais uma fala do campee lissandra]', '[bonus: e lissandra no microfone]'],
  braum: ['[quote do campee braum]', '[outra frase do campee braum]', '[mais uma fala do campee braum]', '[bonus: e braum no microfone]'],
  olaf: ['[quote do campee olaf]', '[outra frase do campee olaf]', '[mais uma fala do campee olaf]', '[bonus: e olaf no microfone]'],
  tryndamere: ['[quote do campee tryndamere]', '[outra frase do campee tryndamere]', '[mais uma fala do campee tryndamere]', '[bonus: e tryndamere no microfone]'],
  gragas: ['[quote do campee gragas]', '[outra frase do campee gragas]', '[mais uma fala do campee gragas]', '[bonus: e gragas no microfone]'],
  ornn: ['[quote do campee ornn]', '[outra frase do campee ornn]', '[mais uma fala do campee ornn]', '[bonus: e ornn no microfone]'],
  aurora: ['[quote do campee aurora]', '[outra frase do campee aurora]', '[mais uma fala do campee aurora]', '[bonus: e aurora no microfone]'],
  irelia: ['[quote do campee irelia]', '[outra frase do campee irelia]', '[mais uma fala do campee irelia]', '[bonus: e irelia no microfone]'],
  karma: ['[quote do campee karma]', '[outra frase do campee karma]', '[mais uma fala do campee karma]', '[bonus: e karma no microfone]'],
  varus: ['[quote do campee varus]', '[outra frase do campee varus]', '[mais uma fala do campee varus]', '[bonus: e varus no microfone]'],
  xayah: ['[quote do campee xayah]', '[outra frase do campee xayah]', '[mais uma fala do campee xayah]', '[bonus: e xayah no microfone]'],
  rakan: ['[quote do campee rakan]', '[outra frase do campee rakan]', '[mais uma fala do campee rakan]', '[bonus: e rakan no microfone]'],
  wukong: ['[quote do campee wukong]', '[outra frase do campee wukong]', '[mais uma fala do campee wukong]', '[bonus: e wukong no microfone]'],
  syndra: ['[quote do campee syndra]', '[outra frase do campee syndra]', '[mais uma fala do campee syndra]', '[bonus: e syndra no microfone]'],
  lillia: ['[quote do campee lillia]', '[outra frase do campee lillia]', '[mais uma fala do campee lillia]', '[bonus: e lillia no microfone]'],
  hwei: ['[quote do campee hwei]', '[outra frase do campee hwei]', '[mais uma fala do campee hwei]', '[bonus: e hwei no microfone]'],
  rengar: ['[quote do campee rengar]', '[outra frase do campee rengar]', '[mais uma fala do campee rengar]', '[bonus: e rengar no microfone]'],
  nidalee: ['[quote do campee nidalee]', '[outra frase do campee nidalee]', '[mais uma fala do campee nidalee]', '[bonus: e nidalee no microfone]'],
  qiyana: ['[quote do campee qiyana]', '[outra frase do campee qiyana]', '[mais uma fala do campee qiyana]', '[bonus: e qiyana no microfone]'],
  neeko: ['[quote do campee neeko]', '[outra frase do campee neeko]', '[mais uma fala do campee neeko]', '[bonus: e neeko no microfone]'],
  zyra: ['[quote do campee zyra]', '[outra frase do campee zyra]', '[mais uma fala do campee zyra]', '[bonus: e zyra no microfone]'],
  ivern: ['[quote do campee ivern]', '[outra frase do campee ivern]', '[mais uma fala do campee ivern]', '[bonus: e ivern no microfone]'],
  milio: ['[quote do campee milio]', '[outra frase do campee milio]', '[mais uma fala do campee milio]', '[bonus: e milio no microfone]'],
  aurelionsol: ['[quote do campee aurelionsol]', '[outra frase do campee aurelionsol]', '[mais uma fala do campee aurelionsol]', '[bonus: e aurelionsol no microfone]'],
  pantheon: ['[quote do campee pantheon]', '[outra frase do campee pantheon]', '[mais uma fala do campee pantheon]', '[bonus: e pantheon no microfone]'],
  zoe: ['[quote do campee zoe]', '[outra frase do campee zoe]', '[mais uma fala do campee zoe]', '[bonus: e zoe no microfone]'],
  taric: ['[quote do campee taric]', '[outra frase do campee taric]', '[mais uma fala do campee taric]', '[bonus: e taric no microfone]'],
  aphelios: ['[quote do campee aphelios]', '[outra frase do campee aphelios]', '[mais uma fala do campee aphelios]', '[bonus: e aphelios no microfone]'],
  draven: ['[quote do campee draven]', '[outra frase do campee draven]', '[mais uma fala do campee draven]', '[bonus: e draven no microfone]'],
  swain: ['[quote do campee swain]', '[outra frase do campee swain]', '[mais uma fala do campee swain]', '[bonus: e swain no microfone]'],
  vladimir: ['[quote do campee vladimir]', '[outra frase do campee vladimir]', '[mais uma fala do campee vladimir]', '[bonus: e vladimir no microfone]'],
  camille: ['[quote do campee camille]', '[outra frase do campee camille]', '[mais uma fala do campee camille]', '[bonus: e camille no microfone]'],
  elise: ['[quote do campee elise]', '[outra frase do campee elise]', '[mais uma fala do campee elise]', '[bonus: e elise no microfone]'],
  evelynn: ['[quote do campee evelynn]', '[outra frase do campee evelynn]', '[mais uma fala do campee evelynn]', '[bonus: e evelynn no microfone]'],
  hecarim: ['[quote do campee hecarim]', '[outra frase do campee hecarim]', '[mais uma fala do campee hecarim]', '[bonus: e hecarim no microfone]'],
  kalista: ['[quote do campee kalista]', '[outra frase do campee kalista]', '[mais uma fala do campee kalista]', '[bonus: e kalista no microfone]'],
  mordekaiser: ['[quote do campee mordekaiser]', '[outra frase do campee mordekaiser]', '[mais uma fala do campee mordekaiser]', '[bonus: e mordekaiser no microfone]'],
  nocturne: ['[quote do campee nocturne]', '[outra frase do campee nocturne]', '[mais uma fala do campee nocturne]', '[bonus: e nocturne no microfone]'],
  yorick: ['[quote do campee yorick]', '[outra frase do campee yorick]', '[mais uma fala do campee yorick]', '[bonus: e yorick no microfone]'],
  zed_shadow: ['[quote do campee zed_shadow]', '[outra frase do campee zed_shadow]', '[mais uma fala do campee zed_shadow]', '[bonus: e zed_shadow no microfone]'],
  karthus: ['[quote do campee karthus]', '[outra frase do campee karthus]', '[mais uma fala do campee karthus]', '[bonus: e karthus no microfone]'],
  velkoz: ['[quote do campee velkoz]', '[outra frase do campee velkoz]', '[mais uma fala do campee velkoz]', '[bonus: e velkoz no microfone]'],
  rek_sai: ['[quote do campee rek_sai]', '[outra frase do campee rek_sai]', '[mais uma fala do campee rek_sai]', '[bonus: e rek_sai no microfone]'],
  cho_gath: ['[quote do campee cho_gath]', '[outra frase do campee cho_gath]', '[mais uma fala do campee cho_gath]', '[bonus: e cho_gath no microfone]'],
  belveth: ['[quote do campee belveth]', '[outra frase do campee belveth]', '[mais uma fala do campee belveth]', '[bonus: e belveth no microfone]'],
  briar: ['[quote do campee briar]', '[outra frase do campee briar]', '[mais uma fala do campee briar]', '[bonus: e briar no microfone]'],
  azir: ['[quote do campee azir]', '[outra frase do campee azir]', '[mais uma fala do campee azir]', '[bonus: e azir no microfone]'],
  nasus_renekton: ['[quote do campee nasus_renekton]', '[outra frase do campee nasus_renekton]', '[mais uma fala do campee nasus_renekton]', '[bonus: e nasus_renekton no microfone]'],
  skarner: ['[quote do campee skarner]', '[outra frase do campee skarner]', '[mais uma fala do campee skarner]', '[bonus: e skarner no microfone]'],
  xerath: ['[quote do campee xerath]', '[outra frase do campee xerath]', '[mais uma fala do campee xerath]', '[bonus: e xerath no microfone]'],
  zilean: ['[quote do campee zilean]', '[outra frase do campee zilean]', '[mais uma fala do campee zilean]', '[bonus: e zilean no microfone]'],
  ambessa: ['[quote do campee ambessa]', '[outra frase do campee ambessa]', '[mais uma fala do campee ambessa]', '[bonus: e ambessa no microfone]'],
  mel: ['[quote do campee mel]', '[outra frase do campee mel]', '[mais uma fala do campee mel]', '[bonus: e mel no microfone]'],
  leesin: ['[quote do campee leesin]', '[outra frase do campee leesin]', '[mais uma fala do campee leesin]', '[bonus: e leesin no microfone]'],
  masteryi: ['[quote do campee masteryi]', '[outra frase do campee masteryi]', '[mais uma fala do campee masteryi]', '[bonus: e masteryi no microfone]'],
  cassiopeia: ['[quote do campee cassiopeia]', '[outra frase do campee cassiopeia]', '[mais uma fala do campee cassiopeia]', '[bonus: e cassiopeia no microfone]'],
  sion: ['[quote do campee sion]', '[outra frase do campee sion]', '[mais uma fala do campee sion]', '[bonus: e sion no microfone]'],
  talon: ['[quote do campee talon]', '[outra frase do campee talon]', '[mais uma fala do campee talon]', '[bonus: e talon no microfone]'],
  samira: ['[quote do campee samira]', '[outra frase do campee samira]', '[mais uma fala do campee samira]', '[bonus: e samira no microfone]'],
  leblanc: ['[quote do campee leblanc]', '[outra frase do campee leblanc]', '[mais uma fala do campee leblanc]', '[bonus: e leblanc no microfone]'],
  smolder: ['[quote do campee smolder]', '[outra frase do campee smolder]', '[mais uma fala do campee smolder]', '[bonus: e smolder no microfone]'],
  ksante: ['[quote do campee ksante]', '[outra frase do campee ksante]', '[mais uma fala do campee ksante]', '[bonus: e ksante no microfone]'],
  kayn: ['[quote do campee kayn]', '[outra frase do campee kayn]', '[mais uma fala do campee kayn]', '[bonus: e kayn no microfone]'],
  rell: ['[quote do campee rell]', '[outra frase do campee rell]', '[mais uma fala do campee rell]', '[bonus: e rell no microfone]'],
  annie: ['[quote do campee annie]', '[outra frase do campee annie]', '[mais uma fala do campee annie]', '[bonus: e annie no microfone]'],
  vi: ['[quote do campee vi]', '[outra frase do campee vi]', '[mais uma fala do campee vi]', '[bonus: e vi no microfone]'],
  jayce: ['[quote do campee jayce]', '[outra frase do campee jayce]', '[mais uma fala do campee jayce]', '[bonus: e jayce no microfone]'],
  seraphine: ['[quote do campee seraphine]', '[outra frase do campee seraphine]', '[mais uma fala do campee seraphine]', '[bonus: e seraphine no microfone]'],
  viktor: ['[quote do campee viktor]', '[outra frase do campee viktor]', '[mais uma fala do campee viktor]', '[bonus: e viktor no microfone]'],
  renata: ['[quote do campee renata]', '[outra frase do campee renata]', '[mais uma fala do campee renata]', '[bonus: e renata no microfone]'],
  kindred: ['[quote do campee kindred]', '[outra frase do campee kindred]', '[mais uma fala do campee kindred]', '[bonus: e kindred no microfone]'],
  jhin: ['[quote do campee jhin]', '[outra frase do campee jhin]', '[mais uma fala do campee jhin]', '[bonus: e jhin no microfone]'],
  bard: ['[quote do campee bard]', '[outra frase do campee bard]', '[mais uma fala do campee bard]', '[bonus: e bard no microfone]'],
  alistar: ['[quote do campee alistar]', '[outra frase do campee alistar]', '[mais uma fala do campee alistar]', '[bonus: e alistar no microfone]'],
  fiddlesticks: ['[quote do campee fiddlesticks]', '[outra frase do campee fiddlesticks]', '[mais uma fala do campee fiddlesticks]', '[bonus: e fiddlesticks no microfone]'],
  jax: ['[quote do campee jax]', '[outra frase do campee jax]', '[mais uma fala do campee jax]', '[bonus: e jax no microfone]'],
  ryze: ['[quote do campee ryze]', '[outra frase do campee ryze]', '[mais uma fala do campee ryze]', '[bonus: e ryze no microfone]'],
  shaco: ['[quote do campee shaco]', '[outra frase do campee shaco]', '[mais uma fala do campee shaco]', '[bonus: e shaco no microfone]'],
  nami: ['[quote do campee nami]', '[outra frase do campee nami]', '[mais uma fala do campee nami]', '[bonus: e nami no microfone]'],
  brand: ['[quote do campee brand]', '[outra frase do campee brand]', '[mais uma fala do campee brand]', '[bonus: e brand no microfone]'],
  viego: ['[quote do campee viego]', '[outra frase do campee viego]', '[mais uma fala do campee viego]', '[bonus: e viego no microfone]'],
  vex: ['[quote do campee vex]', '[outra frase do campee vex]', '[mais uma fala do campee vex]', '[bonus: e vex no microfone]'],
  maokai: ['[quote do campee maokai]', '[outra frase do campee maokai]', '[mais uma fala do campee maokai]', '[bonus: e maokai no microfone]'],
  renekton: ['[quote do campee renekton]', '[outra frase do campee renekton]', '[mais uma fala do campee renekton]', '[bonus: e renekton no microfone]'],
  amumu: ['[quote do campee amumu]', '[outra frase do campee amumu]', '[mais uma fala do campee amumu]', '[bonus: e amumu no microfone]'],
  taliyah: ['[quote do campee taliyah]', '[outra frase do campee taliyah]', '[mais uma fala do campee taliyah]', '[bonus: e taliyah no microfone]'],
  akshan: ['[quote do campee akshan]', '[outra frase do campee akshan]', '[mais uma fala do campee akshan]', '[bonus: e akshan no microfone]'],
  naafiri: ['[quote do campee naafiri]', '[outra frase do campee naafiri]', '[mais uma fala do campee naafiri]', '[bonus: e naafiri no microfone]'],
  kassadin: ['[quote do campee kassadin]', '[outra frase do campee kassadin]', '[mais uma fala do campee kassadin]', '[bonus: e kassadin no microfone]'],
  kogmaw: ['[quote do campee kogmaw]', '[outra frase do campee kogmaw]', '[mais uma fala do campee kogmaw]', '[bonus: e kogmaw no microfone]'],
  chogath: ['[quote do campee chogath]', '[outra frase do campee chogath]', '[mais uma fala do campee chogath]', '[bonus: e chogath no microfone]'],
  khazix: ['[quote do campee khazix]', '[outra frase do campee khazix]', '[mais uma fala do campee khazix]', '[bonus: e khazix no microfone]'],
  reksai: ['[quote do campee reksai]', '[outra frase do campee reksai]', '[mais uma fala do campee reksai]', '[bonus: e reksai no microfone]'],
  malzahar: ['[quote do campee malzahar]', '[outra frase do campee malzahar]', '[mais uma fala do campee malzahar]', '[bonus: e malzahar no microfone]'],
  kaisa: ['[quote do campee kaisa]', '[outra frase do campee kaisa]', '[mais uma fala do campee kaisa]', '[bonus: e kaisa no microfone]'],
  ziggs: ['[quote do campee ziggs]', '[outra frase do campee ziggs]', '[mais uma fala do campee ziggs]', '[bonus: e ziggs no microfone]'],
  zac: ['[quote do campee zac]', '[outra frase do campee zac]', '[mais uma fala do campee zac]', '[bonus: e zac no microfone]'],
  drmundo: ['[quote do campee drmundo]', '[outra frase do campee drmundo]', '[mais uma fala do campee drmundo]', '[bonus: e drmundo no microfone]'],
  singed: ['[quote do campee singed]', '[outra frase do campee singed]', '[mais uma fala do campee singed]', '[bonus: e singed no microfone]'],
  twitch: ['[quote do campee twitch]', '[outra frase do campee twitch]', '[mais uma fala do campee twitch]', '[bonus: e twitch no microfone]'],
  blitzcrank: ['[quote do campee blitzcrank]', '[outra frase do campee blitzcrank]', '[mais uma fala do campee blitzcrank]', '[bonus: e blitzcrank no microfone]'],
  urgot: ['[quote do campee urgot]', '[outra frase do campee urgot]', '[mais uma fala do campee urgot]', '[bonus: e urgot no microfone]'],
  janna: ['[quote do campee janna]', '[outra frase do campee janna]', '[mais uma fala do campee janna]', '[bonus: e janna no microfone]'],
  warwick: ['[quote do campee warwick]', '[outra frase do campee warwick]', '[mais uma fala do campee warwick]', '[bonus: e warwick no microfone]'],
  zeri: ['[quote do campee zeri]', '[outra frase do campee zeri]', '[mais uma fala do campee zeri]', '[bonus: e zeri no microfone]'],
}

/**
 * Escolhe uma quote aleatoria para o campeao. Se o campeao nao estiver
 * no map, retorna um placeholder generico.
 */
export function getRandomQuoteForChampion(championId: string): string {
  const list = CHAMPION_QUOTES[championId]
  if (!list || list.length === 0) {
    return `[quote do campee ${championId}]`
  }
  const idx = Math.floor(Math.random() * list.length)
  return list[idx]
}

/**
 * Deterministico: hash(dateKey) -> index da quote para o campeao-alvo.
 * Garante que todos os jogadores do mesmo dia recebem a mesma quote.
 */
export function getQuoteForChampionForDate(
  championId: string,
  dateKey: string
): string {
  const list = CHAMPION_QUOTES[championId]
  if (!list || list.length === 0) {
    return `[quote do campee ${championId}]`
  }
  let h = 0x811c9dc5
  for (let i = 0; i < dateKey.length; i++) {
    h ^= dateKey.charCodeAt(i)
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0
  }
  const idx = h % list.length
  return list[idx]
}
