// src/pages/games/pitaco-atributos/auditors.ts
//
// Banco de 30 auditores ficticios do escritorio PITACO. Cada um tem
// os atributos categoricos necessarios para o jogo PITACO Atributos
// (cargo, equipe, senioridade, turno, cidade, hobby).
//
// Distribuicao alvo:
//   - 5 cargos x ~6 auditores = 30 (5 cargos: Estagiario/Auditor/Analista/Chefe/Gerente)
//   - 6 equipes cobertas (Plataforma, Growth, Compliance, Operacoes, RH, Financeiro, Marketing, Tech)
//   - senioridade 1-5 distribuida (1=Junior ... 5=Principal)
//   - 4 turnos (manha, tarde, integral, flex)
//   - 5 cidades (SP, RJ, MG, RS, BA)
//   - 6 hobbies (futebol, leitura, games, cozinha, caminhada, cafe)
//
// Os IDs sao estaveis (auditor-001 .. auditor-030) para permitir
// referencia em testes e saves do localStorage.

import type { Auditor } from './types'

export const AUDITORES: Auditor[] = [
  {
    id: 'auditor-001',
    nome: 'Joana Silva',
    apelido: 'Joana',
    cargo: 'Auditor',
    equipe: 'Compliance',
    senioridade: 3,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'leitura',
    emoji: '📚',
  },
  {
    id: 'auditor-002',
    nome: 'Pedro Costa',
    apelido: 'Pedro',
    cargo: 'Analista',
    equipe: 'Plataforma',
    senioridade: 3,
    turno: 'flex',
    cidade: 'RJ',
    hobby: 'futebol',
    emoji: '⚽',
  },
  {
    id: 'auditor-003',
    nome: 'Marina Souza',
    apelido: 'Marina',
    cargo: 'Gerente',
    equipe: 'RH',
    senioridade: 4,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '☕',
  },
  {
    id: 'auditor-004',
    nome: 'Rafael Lima',
    apelido: 'Rafa',
    cargo: 'Analista',
    equipe: 'Tech',
    senioridade: 3,
    turno: 'flex',
    cidade: 'MG',
    hobby: 'games',
    emoji: '🎮',
  },
  {
    id: 'auditor-005',
    nome: 'Camila Pitaco',
    apelido: 'Cami',
    cargo: 'Estagiario',
    equipe: 'Marketing',
    senioridade: 1,
    turno: 'manha',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '🐤',
  },
  {
    id: 'auditor-006',
    nome: 'Bruno Cheffe',
    apelido: 'Bruno',
    cargo: 'Chefe',
    equipe: 'Operacoes',
    senioridade: 4,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '👔',
  },
  {
    id: 'auditor-007',
    nome: 'Leticia Reuniao',
    apelido: 'Le',
    cargo: 'Chefe',
    equipe: 'Plataforma',
    senioridade: 4,
    turno: 'integral',
    cidade: 'RJ',
    hobby: 'caminhada',
    emoji: '🗓️',
  },
  {
    id: 'auditor-008',
    nome: 'Tiago Cafe',
    apelido: 'Tiago',
    cargo: 'Analista',
    equipe: 'Tech',
    senioridade: 3,
    turno: 'flex',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '💻',
  },
  {
    id: 'auditor-009',
    nome: 'Ana Design',
    apelido: 'Aninha',
    cargo: 'Analista',
    equipe: 'Marketing',
    senioridade: 3,
    turno: 'flex',
    cidade: 'BA',
    hobby: 'leitura',
    emoji: '🎨',
  },
  {
    id: 'auditor-010',
    nome: 'Lucas RH',
    apelido: 'Luca',
    cargo: 'Auditor',
    equipe: 'RH',
    senioridade: 2,
    turno: 'integral',
    cidade: 'MG',
    hobby: 'futebol',
    emoji: '🤝',
  },
  {
    id: 'auditor-011',
    nome: 'Sofia Financeiro',
    apelido: 'Sofi',
    cargo: 'Analista',
    equipe: 'Financeiro',
    senioridade: 3,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'leitura',
    emoji: '🧾',
  },
  {
    id: 'auditor-012',
    nome: 'Diego Juridico',
    apelido: 'Die',
    cargo: 'Auditor',
    equipe: 'Compliance',
    senioridade: 4,
    turno: 'integral',
    cidade: 'RJ',
    hobby: 'leitura',
    emoji: '⚖️',
  },
  {
    id: 'auditor-013',
    nome: 'Patricia Marketing',
    apelido: 'Pati',
    cargo: 'Gerente',
    equipe: 'Marketing',
    senioridade: 4,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'caminhada',
    emoji: '📣',
  },
  {
    id: 'auditor-014',
    nome: 'Renan Vendas',
    apelido: 'Renan',
    cargo: 'Analista',
    equipe: 'Growth',
    senioridade: 2,
    turno: 'manha',
    cidade: 'BA',
    hobby: 'futebol',
    emoji: '📞',
  },
  {
    id: 'auditor-015',
    nome: 'Juliana Suporte',
    apelido: 'Ju',
    cargo: 'Auditor',
    equipe: 'Operacoes',
    senioridade: 2,
    turno: 'tarde',
    cidade: 'RS',
    hobby: 'cozinha',
    emoji: '🎧',
  },
  {
    id: 'auditor-016',
    nome: 'Marcos Infra',
    apelido: 'Marcao',
    cargo: 'Chefe',
    equipe: 'Tech',
    senioridade: 5,
    turno: 'flex',
    cidade: 'SP',
    hobby: 'games',
    emoji: '🖥️',
  },
  {
    id: 'auditor-017',
    nome: 'Carolina Mobile',
    apelido: 'Carol',
    cargo: 'Analista',
    equipe: 'Tech',
    senioridade: 3,
    turno: 'flex',
    cidade: 'RJ',
    hobby: 'cozinha',
    emoji: '📱',
  },
  {
    id: 'auditor-018',
    nome: 'Felipe Android',
    apelido: 'Fe',
    cargo: 'Analista',
    equipe: 'Tech',
    senioridade: 3,
    turno: 'integral',
    cidade: 'MG',
    hobby: 'games',
    emoji: '🤖',
  },
  {
    id: 'auditor-019',
    nome: 'Isabela QA',
    apelido: 'Isa',
    cargo: 'Auditor',
    equipe: 'Plataforma',
    senioridade: 3,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'leitura',
    emoji: '🐛',
  },
  {
    id: 'auditor-020',
    nome: 'Gustavo Seguranca',
    apelido: 'Gus',
    cargo: 'Auditor',
    equipe: 'Compliance',
    senioridade: 4,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'games',
    emoji: '🛡️',
  },
  {
    id: 'auditor-021',
    nome: 'Paula Produto',
    apelido: 'Paulinha',
    cargo: 'Gerente',
    equipe: 'Plataforma',
    senioridade: 4,
    turno: 'integral',
    cidade: 'RJ',
    hobby: 'caminhada',
    emoji: '🧭',
  },
  {
    id: 'auditor-022',
    nome: 'Helen UX',
    apelido: 'Hel',
    cargo: 'Auditor',
    equipe: 'Plataforma',
    senioridade: 2,
    turno: 'flex',
    cidade: 'BA',
    hobby: 'leitura',
    emoji: '🗣️',
  },
  {
    id: 'auditor-023',
    nome: 'Andre Backend',
    apelido: 'De',
    cargo: 'Chefe',
    equipe: 'Tech',
    senioridade: 5,
    turno: 'flex',
    cidade: 'SP',
    hobby: 'games',
    emoji: '🧱',
  },
  {
    id: 'auditor-024',
    nome: 'Natalia Frontend',
    apelido: 'Nat',
    cargo: 'Analista',
    equipe: 'Tech',
    senioridade: 2,
    turno: 'flex',
    cidade: 'RS',
    hobby: 'cafe',
    emoji: '✨',
  },
  {
    id: 'auditor-025',
    nome: 'Rodrigo Estrategia',
    apelido: 'Drigo',
    cargo: 'Diretor',
    equipe: 'Operacoes',
    senioridade: 5,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'caminhada',
    emoji: '🧠',
  },
  {
    id: 'auditor-026',
    nome: 'Vivian Tesouraria',
    apelido: 'Viv',
    cargo: 'Chefe',
    equipe: 'Financeiro',
    senioridade: 4,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '🏦',
  },
  {
    id: 'auditor-027',
    nome: 'Caio Compras',
    apelido: 'Caio',
    cargo: 'Analista',
    equipe: 'Financeiro',
    senioridade: 3,
    turno: 'integral',
    cidade: 'RJ',
    hobby: 'futebol',
    emoji: '🛒',
  },
  {
    id: 'auditor-028',
    nome: 'Beatriz Facilites',
    apelido: 'Bea',
    cargo: 'Auditor',
    equipe: 'Operacoes',
    senioridade: 2,
    turno: 'manha',
    cidade: 'MG',
    hobby: 'cozinha',
    emoji: '🧹',
  },
  {
    id: 'auditor-029',
    nome: 'Thiago Logistica',
    apelido: 'Thi',
    cargo: 'Analista',
    equipe: 'Operacoes',
    senioridade: 3,
    turno: 'tarde',
    cidade: 'BA',
    hobby: 'futebol',
    emoji: '🚚',
  },
  {
    id: 'auditor-030',
    nome: 'Priscila Treinamento',
    apelido: 'Pri',
    cargo: 'Auditor',
    equipe: 'RH',
    senioridade: 3,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'caminhada',
    emoji: '🎓',
  },
  {
    id: 'auditor-031',
    nome: 'Lucas DevOps',
    apelido: 'Lukas',
    cargo: 'Auditor',
    equipe: 'Tech',
    senioridade: 4,
    turno: 'flex',
    cidade: 'RS',
    hobby: 'games',
    emoji: '🐳',
  },
  {
    id: 'auditor-032',
    nome: 'Vanessa BI',
    apelido: 'Van',
    cargo: 'Analista',
    equipe: 'Financeiro',
    senioridade: 3,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '📊',
  },
  {
    id: 'auditor-033',
    nome: 'Eduardo Growth',
    apelido: 'Du',
    cargo: 'Chefe',
    equipe: 'Growth',
    senioridade: 4,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'futebol',
    emoji: '📈',
  },
  {
    id: 'auditor-034',
    nome: 'Beatriz Estagiaria',
    apelido: 'Bia',
    cargo: 'Estagiario',
    equipe: 'Tech',
    senioridade: 1,
    turno: 'manha',
    cidade: 'RJ',
    hobby: 'games',
    emoji: '🥤',
  },
  {
    id: 'auditor-035',
    nome: 'Otavio Diretor',
    apelido: 'Tavio',
    cargo: 'Diretor',
    equipe: 'Compliance',
    senioridade: 5,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '🪑',
  },
  {
    id: 'auditor-036',
    nome: 'Mariana Estagiaria',
    apelido: 'Mari',
    cargo: 'Estagiario',
    equipe: 'RH',
    senioridade: 1,
    turno: 'tarde',
    cidade: 'MG',
    hobby: 'leitura',
    emoji: '🌱',
  },
  {
    id: 'auditor-037',
    nome: 'Henrique Pleno',
    apelido: 'Henri',
    cargo: 'Auditor',
    equipe: 'Growth',
    senioridade: 2,
    turno: 'flex',
    cidade: 'BA',
    hobby: 'caminhada',
    emoji: '🎯',
  },
  {
    id: 'auditor-038',
    nome: 'Larissa Marketing',
    apelido: 'Lari',
    cargo: 'Estagiario',
    equipe: 'Marketing',
    senioridade: 1,
    turno: 'manha',
    cidade: 'SP',
    hobby: 'cafe',
    emoji: '📱',
  },
  {
    id: 'auditor-039',
    nome: 'Igor Plataforma',
    apelido: 'Igor',
    cargo: 'Diretor',
    equipe: 'Plataforma',
    senioridade: 5,
    turno: 'integral',
    cidade: 'SP',
    hobby: 'caminhada',
    emoji: '🗺️',
  },
  {
    id: 'auditor-040',
    nome: 'Renata Compliance',
    apelido: 'Re',
    cargo: 'Gerente',
    equipe: 'Compliance',
    senioridade: 4,
    turno: 'integral',
    cidade: 'RJ',
    hobby: 'leitura',
    emoji: '📑',
  },
]

/**
 * Busca auditor por id (estavel: auditor-001 .. auditor-040).
 */
export function findAuditorById(id: string): Auditor | undefined {
  return AUDITORES.find((a) => a.id === id)
}

/**
 * Busca auditor por nome ou apelido (normalizado, sem acento).
 * Retorna undefined se nada bater.
 */
export function findAuditorByQuery(query: string): Auditor | undefined {
  const norm = query
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\w\s]/g, '')
    .toLowerCase()
    .trim()
  if (!norm) return undefined
  return AUDITORES.find((a) => {
    const fullNorm = `${a.nome} ${a.apelido}`
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^\w\s]/g, '')
      .toLowerCase()
    return fullNorm.includes(norm)
  })
}
