// src/pages/games/narutodle/characters.ts
//
// 40 personagens principais de Naruto Shippuden com seus atributos
// categoricos. Dados baseados nas informacoes canonicas da serie
// (databooks, anime/manga, informacoes amplamente aceitas pela fandom).
//
// Convencoes:
//  - 'Nenhum' (cla) para personagens sem cla canonico.
//  - 'Nenhum' (kekkei genkai) para personagens sem KG.
//  - 'Nenhum' (elemento) para personagens sem afinidade elemental
//    canonica claramente definida.
//  - Para Akatsuki e similares, 'rank' = rank na vila de origem.
//  - 'vila: Akatsuki' e usada para personagens que operaram pela
//    Akatsuki no periodo Shippuden (Pain, Konan, Zetsu, etc).
//
// 40 personagens = 40+ dias unicos de jogo sem repeticao no
// primeiro ciclo. Lista pode crescer no futuro sem quebrar o save
// (o save guarda o id, nao o indice).

import type { NarutodleCharacter } from './types'

export const NARUTO_CHARACTERS: NarutodleCharacter[] = [
  {
    id: 'naruto',
    name: 'Naruto Uzumaki',
    clan: 'Uzumaki',
    vila: 'Konoha',
    rank: 'Kage',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Vento',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'sasuke',
    name: 'Sasuke Uchiha',
    clan: 'Uchiha',
    vila: 'Konoha',
    rank: 'Genin',
    kekkeiGenkai: 'Sharingan',
    elemento: 'Trovão',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'sakura',
    name: 'Sakura Haruno',
    clan: 'Haruno',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Konoha',
    genero: 'F',
  },
  {
    id: 'kakashi',
    name: 'Kakashi Hatake',
    clan: 'Hatake',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Sharingan',
    elemento: 'Trovão',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'itachi',
    name: 'Itachi Uchiha',
    clan: 'Uchiha',
    vila: 'Akatsuki',
    rank: 'ANBU',
    kekkeiGenkai: 'Sharingan',
    elemento: 'Fogo',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'madara',
    name: 'Madara Uchiha',
    clan: 'Uchiha',
    vila: 'Akatsuki',
    rank: 'Kage',
    kekkeiGenkai: 'Rinnegan',
    elemento: 'Fogo',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'hashirama',
    name: 'Hashirama Senju',
    clan: 'Senju',
    vila: 'Konoha',
    rank: 'Kage',
    kekkeiGenkai: 'Wood Release',
    elemento: 'Água',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'tobirama',
    name: 'Tobirama Senju',
    clan: 'Senju',
    vila: 'Konoha',
    rank: 'Kage',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Água',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'minato',
    name: 'Minato Namikaze',
    clan: 'Namikaze',
    vila: 'Konoha',
    rank: 'Kage',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Trovão',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'kushina',
    name: 'Kushina Uzumaki',
    clan: 'Uzumaki',
    vila: 'Konoha',
    rank: 'Chunin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Vento',
    afiliacao: 'Konoha',
    genero: 'F',
  },
  {
    id: 'jiraiya',
    name: 'Jiraiya',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'Sannin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Fogo',
    afiliacao: 'Sannin',
    genero: 'M',
  },
  {
    id: 'tsunade',
    name: 'Tsunade',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'Kage',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Sannin',
    genero: 'F',
  },
  {
    id: 'orochimaru',
    name: 'Orochimaru',
    clan: 'Nenhum',
    vila: 'Otogakure',
    rank: 'Sannin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Vento',
    afiliacao: 'Sannin',
    genero: 'M',
  },
  {
    id: 'kabuto',
    name: 'Kabuto Yakushi',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'ANBU',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Yin',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'shisui',
    name: 'Shisui Uchiha',
    clan: 'Uchiha',
    vila: 'Konoha',
    rank: 'ANBU',
    kekkeiGenkai: 'Sharingan',
    elemento: 'Fogo',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'gaara',
    name: 'Gaara',
    clan: 'Nenhum',
    vila: 'Suna',
    rank: 'Kage',
    kekkeiGenkai: 'Magnet Release',
    elemento: 'Terra',
    afiliacao: 'Outros',
    genero: 'M',
  },
  {
    id: 'temari',
    name: 'Temari',
    clan: 'Nenhum',
    vila: 'Suna',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Vento',
    afiliacao: 'Outros',
    genero: 'F',
  },
  {
    id: 'kankuro',
    name: 'Kankuro',
    clan: 'Nenhum',
    vila: 'Suna',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Outros',
    genero: 'M',
  },
  {
    id: 'lee',
    name: 'Rock Lee',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Trovão',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'neji',
    name: 'Neji Hyuga',
    clan: 'Hyuga',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Byakugan',
    elemento: 'Fogo',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'tenten',
    name: 'Tenten',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Konoha',
    genero: 'F',
  },
  {
    id: 'hinata',
    name: 'Hinata Hyuga',
    clan: 'Hyuga',
    vila: 'Konoha',
    rank: 'Chunin',
    kekkeiGenkai: 'Byakugan',
    elemento: 'Fogo',
    afiliacao: 'Konoha',
    genero: 'F',
  },
  {
    id: 'ino',
    name: 'Ino Yamanaka',
    clan: 'Yamanaka',
    vila: 'Konoha',
    rank: 'Chunin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Konoha',
    genero: 'F',
  },
  {
    id: 'shikamaru',
    name: 'Shikamaru Nara',
    clan: 'Nara',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'choji',
    name: 'Choji Akimichi',
    clan: 'Akimichi',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Fogo',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'shino',
    name: 'Shino Aburame',
    clan: 'Aburame',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'kiba',
    name: 'Kiba Inuzuka',
    clan: 'Inuzuka',
    vila: 'Konoha',
    rank: 'Chunin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Vento',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'akamaru',
    name: 'Akamaru',
    clan: 'Inuzuka',
    vila: 'Konoha',
    rank: 'Genin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Nenhum',
    afiliacao: 'Konoha',
    genero: 'Outro',
  },
  {
    id: 'sai',
    name: 'Sai',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'ANBU',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'yamato',
    name: 'Yamato',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'ANBU',
    kekkeiGenkai: 'Wood Release',
    elemento: 'Água',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'asuma',
    name: 'Asuma Sarutobi',
    clan: 'Sarutobi',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Fogo',
    afiliacao: 'Konoha',
    genero: 'M',
  },
  {
    id: 'kurenai',
    name: 'Kurenai Yuhi',
    clan: 'Nenhum',
    vila: 'Konoha',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Yin',
    afiliacao: 'Konoha',
    genero: 'F',
  },
  {
    id: 'hidan',
    name: 'Hidan',
    clan: 'Nenhum',
    vila: 'Akatsuki',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Nenhum',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'kakuzu',
    name: 'Kakuzu',
    clan: 'Nenhum',
    vila: 'Akatsuki',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'deidara',
    name: 'Deidara',
    clan: 'Nenhum',
    vila: 'Akatsuki',
    rank: 'Chunin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Terra',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'sasori',
    name: 'Sasori',
    clan: 'Nenhum',
    vila: 'Akatsuki',
    rank: 'Chunin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Yin',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'konan',
    name: 'Konan',
    clan: 'Nenhum',
    vila: 'Akatsuki',
    rank: 'Chunin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Vento',
    afiliacao: 'Akatsuki',
    genero: 'F',
  },
  {
    id: 'pain',
    name: 'Pain (Nagato)',
    clan: 'Uzumaki',
    vila: 'Akatsuki',
    rank: 'Chunin',
    kekkeiGenkai: 'Rinnegan',
    elemento: 'Yin-Yang',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'obito',
    name: 'Obito Uchiha',
    clan: 'Uchiha',
    vila: 'Akatsuki',
    rank: 'Chunin',
    kekkeiGenkai: 'Sharingan',
    elemento: 'Fogo',
    afiliacao: 'Akatsuki',
    genero: 'M',
  },
  {
    id: 'killer-b',
    name: 'Killer B',
    clan: 'Nenhum',
    vila: 'Kumo',
    rank: 'Jonin',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Trovão',
    afiliacao: 'Outros',
    genero: 'M',
  },
  {
    id: 'ay',
    name: 'Ay (4° Raikage)',
    clan: 'Nenhum',
    vila: 'Kumo',
    rank: 'Kage',
    kekkeiGenkai: 'Nenhum',
    elemento: 'Trovão',
    afiliacao: 'Outros',
    genero: 'M',
  },
  {
    id: 'mei',
    name: 'Mei Terumi',
    clan: 'Nenhum',
    vila: 'Kiri',
    rank: 'Kage',
    kekkeiGenkai: 'Lava Release',
    elemento: 'Água',
    afiliacao: 'Outros',
    genero: 'F',
  },
  {
    id: 'onoki',
    name: 'Onoki',
    clan: 'Nenhum',
    vila: 'Iwa',
    rank: 'Kage',
    kekkeiGenkai: 'Dust Release',
    elemento: 'Terra',
    afiliacao: 'Outros',
    genero: 'M',
  },
]
